/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import React from 'react';
import styles from '../styles/Home.module.css'

export default function Home({tokens, count}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Solana Token List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className='text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-br from-primary to-secondary'>
          Solana Token List
        </h1>

        <p className="text-3xl">
        Total Tokens = {count}
        </p>
        <div>
          <input className='bg-black text-white p-2 rounded-lg w-1/2 md:w-3/4 lg:w-1/2' type="search" placeholder='Filter your search'></input>
        </div>

        <div className={styles.grid}>
<><div className='grid grid-cols-[2fr_2fr_4fr_1fr] gap-1 rounded-lg shadow-2xl p-5'>
  <div className='uppercase font-bold ' >Logo</div>
  <div className='uppercase font-bold '>Symbol</div>
  <div className='uppercase font-bold '>Name</div>
  <div className='uppercase font-bold '>Address</div>
            {tokens.map((token) => (
              <React.Fragment key={token.address} className="hover:bg-secondary">
              <div><img src={token.logoURI} alt={token.name} width="25" height="25"/></div>
              <div>{token.symbol}</div>
              <div>{token.name}</div>
              <div>
              <a target="blank" href={`https://solscan.io/account/${token.address}`}> 🔎 </a>
              {/* {token.address} */}
              </div>
              </React.Fragment>
            ))}
  </div>
</>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://milysec.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
export async function getServerSideProps(context) {
  const hostname = context.req.headers.host;

  const res = await fetch(`http://${hostname}/api/tokens`)
  const data = await res.json()
  
  const count = data.tokens.length;
  const tokens = data.tokens.slice(0,50);

  return { props: { tokens, count } }
}
